### ISSUE TITLE
Wrong link sent to the trustees

### ISSUE THREAD

**Issue by Prajeeths18** [glondu/belenios#37] opened 2021-06-18 08:01 UTC
I was creating and conducting elections in Belenios for finding out loopholes in it.
So, I followed the usual procedure. I first created the admin user, then some voters, questions, and sent the credentials and passwords to them. But, when it comes to the trustees, where we have to send the link for them to generate the decryption key, it seems that the link is sent in a wrong way. 

The link found in the email is: https://belenios.loria.fr/draft/threshold-trustee?token=SwCan9Xj2yEB4W&amp;uuid=Qnzd5shpFWSYhD which on opening shows "Wrong Parameters".

The actual link(which I found out as an admin) is: https://belenios.loria.fr/draft/threshold-trustee?token=SwCan9Xj2yEB4W&uuid=Qnzd5shpFWSYhD

So, as you can see, there is an "amp;" that is somehow added while sending through the mail, which causes the link to be broken.

**Comment by glondu** [comment] 2021-06-18 09:11
I am aware of this bug when the mailto handler is Zimbra, but could not reproduce the bug with other mailers (I tried Thunderbird and Roundcube). I concluded it was a bug in Zimbra. What is your mailto handler?

**Comment by Prajeeths18** [comment] 2021-06-19 06:18
My mailto handler is also Zimbra.

**Comment by glondu** [comment] 2022-11-25 06:55
This has been fixed and released in 1.19.

**Closed by glondu** 2022-11-25 06:55 UTC
